const API_URL="https://api.open-meteo.com/v1/forecast?latitude=37.5665&longitude=126.9780&current=temperature_2m&timezone=Asia%2FSeoul";
const STORAGE_KEY="seoul_temperature_records";
const temperatureEl=document.querySelector("#temperature"),changeEl=document.querySelector("#change"),statusBadge=document.querySelector("#statusBadge"),sourceLink=document.querySelector("#sourceLink"),sourceTime=document.querySelector("#sourceTime"),fetchedTime=document.querySelector("#fetchedTime"),errorMessage=document.querySelector("#errorMessage"),historyEl=document.querySelector("#history"),loadBtn=document.querySelector("#loadBtn"),retryBtn=document.querySelector("#retryBtn");
let records=loadRecords();
function loadRecords(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(saved)?saved:[]}catch{localStorage.removeItem(STORAGE_KEY);return[]}}
function getKstDate(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),value={};parts.forEach(part=>value[part.type]=part.value);return `${value.year}-${value.month}-${value.day}`}
function getKstTime(){return new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",dateStyle:"medium",timeStyle:"medium"}).format(new Date())}
async function fetchTemperature(){statusBadge.textContent="조회 중";statusBadge.className="badge";errorMessage.textContent="실제 공개 원천에서 데이터를 조회하고 있습니다.";errorMessage.className="";loadBtn.disabled=true;try{const response=await fetch(API_URL);if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json(),value=data.current?.temperature_2m,observedAt=data.current?.time,unit=data.current_units?.temperature_2m;if(typeof value!=="number"||!observedAt||unit!=="°C")throw new Error("응답 형식이 예상과 다릅니다.");const record={date:getKstDate(),value,unit,sourceTime:observedAt,fetchedTime:getKstTime(),sourceUrl:API_URL};saveDailyRecord(record);showRecord(record);statusBadge.textContent="정상 · fresh";statusBadge.className="badge fresh";errorMessage.textContent="정상적으로 최신 데이터를 받았습니다.";retryBtn.hidden=true}catch(error){showFailure(`실제 조회 실패: ${error.message}`)}finally{loadBtn.disabled=false}}
function saveDailyRecord(record){const i=records.findIndex(saved=>saved.date===record.date);if(i>=0)records[i]=record;else records.push(record);records.sort((a,b)=>a.date.localeCompare(b.date));localStorage.setItem(STORAGE_KEY,JSON.stringify(records));renderHistory();renderChange()}
function showRecord(record){temperatureEl.textContent=record.value;sourceTime.textContent=`${record.sourceTime} (Asia/Seoul)`;fetchedTime.textContent=record.fetchedTime;sourceLink.href=record.sourceUrl}
function showFailure(message){statusBadge.textContent="오류 · stale";statusBadge.className="badge stale";errorMessage.textContent=`${message} 마지막 정상값을 유지합니다. 인터넷 연결을 확인하고 다시 시도하세요.`;errorMessage.className="error";retryBtn.hidden=false;const last=records.at(-1);if(last)showRecord(last)}
function simulateFailure(type){const messages={denied:"접근 거절(401/403): 외부 원천이 요청을 허용하지 않았습니다.",limit:"호출 제한(429): 요청이 너무 많습니다. 잠시 후 다시 시도하세요.",offline:"오프라인: 네트워크 연결을 확인하세요.",format:"형식 변경: 응답 구조가 예상과 달라 값을 읽지 못했습니다."};if(type==="slow"){statusBadge.textContent="느린 응답";statusBadge.className="badge stale";errorMessage.textContent="응답이 늦어 시간초과 여부를 확인하고 있습니다.";setTimeout(()=>showFailure("느린 응답: 제한 시간 안에 데이터가 오지 않았습니다."),1500);return}showFailure(messages[type])}
function renderHistory(){if(!records.length){historyEl.textContent="아직 저장된 기록이 없습니다.";return}historyEl.innerHTML=records.map(r=>`<div class="record"><strong>${r.date}</strong> · ${r.value}${r.unit}<br>원천 관측: ${r.sourceTime}<br>조회: ${r.fetchedTime}<br>출처: <a href="${r.sourceUrl}" target="_blank">공개 원천 URL</a></div>`).join("")}
function renderChange(){if(records.length<2){changeEl.textContent="어제 대비: 실제 날짜 기록이 한 건 더 필요합니다.";return}const yesterday=records.at(-2),today=records.at(-1),difference=Number((today.value-yesterday.value).toFixed(1)),sign=difference>0?"+":"";changeEl.textContent=`어제 대비: ${sign}${difference}°C (${yesterday.value}°C → ${today.value}°C)`}
loadBtn.addEventListener("click",fetchTemperature);retryBtn.addEventListener("click",fetchTemperature);document.querySelectorAll("[data-error]").forEach(button=>button.addEventListener("click",()=>simulateFailure(button.dataset.error)));renderHistory();renderChange();if(records.length){showRecord(records.at(-1));statusBadge.textContent="저장된 마지막 정상값 · stale";statusBadge.className="badge stale"}
